# Generated by Django 6.0.2 on 2026-03-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_pushsubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ('-pinned', '-created_at')},
        ),
        migrations.AddField(
            model_name='notice',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
