# Generated by Django 6.0.2 on 2026-02-24 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrillCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=160, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_override', models.CharField(blank=True, max_length=120, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_score', models.PositiveIntegerField(default=10)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('drill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainings.drillcatalog')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drills', to='trainings.trainingsession')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DrillScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=4)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drill_scores', to='athletes.athlete')),
                ('rated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('training_drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='trainings.trainingdrill')),
            ],
            options={
                'unique_together': {('training_drill', 'athlete')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Presente'), ('ABSENT', 'Ausente'), ('JUSTIFIED', 'Justificado'), ('LATE', 'Atraso')], default='PRESENT', max_length=12)),
                ('checkin_time', models.TimeField(blank=True, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='athletes.athlete')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='trainings.trainingsession')),
            ],
            options={
                'unique_together': {('training', 'athlete')},
            },
        ),
    ]
