# Generated by Django 6.0.2 on 2026-02-24 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='athletes/photos/')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_city', models.CharField(blank=True, max_length=120, null=True)),
                ('height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('current_position', models.CharField(blank=True, choices=[('QB', 'Quarterback'), ('C', 'Center'), ('WR', 'Wide receiver'), ('RB', 'Running back'), ('DB', 'Defensive back'), ('R', 'Blitz/Rusher'), ('S', 'Safety'), ('CB', 'Corne back')], max_length=5, null=True)),
                ('desired_position', models.CharField(blank=True, choices=[('QB', 'Quarterback'), ('C', 'Center'), ('WR', 'Wide receiver'), ('RB', 'Running back'), ('DB', 'Defensive back'), ('R', 'Blitz/Rusher'), ('S', 'Safety'), ('CB', 'Corne back')], max_length=5, null=True)),
                ('career_notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, help_text='Vincule um usuário para permitir login do atleta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athlete', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
