# Generated by Django 6.0.2 on 2026-03-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0002_savings_goal_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-created_at', '-id')},
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposito', 'Depósito'), ('retirada', 'Retirada')], max_length=10),
        ),
    ]
