# Generated by Django 6.0.2 on 2026-03-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('Ataque', 'Ataque'), ('Defesa', 'Defesa'), ('Bola Parada', 'Bola Parada'), ('Transição', 'Transição'), ('Posse', 'Posse')], max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='playbook/plays/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
