# Generated by Django 5.2.11 on 2026-03-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='category',
            field=models.CharField(blank=True, choices=[('Ataque', 'Ataque'), ('Defesa', 'Defesa')], max_length=30, null=True),
        ),
    ]

# Generated by Django 6.0.2 on 2026-03-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playbook", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="play",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[("Ataque", "Ataque"), ("Defesa", "Defesa")],
                max_length=30,
                null=True,
            ),
        ),
    ]
