# Generated by Django 5.2.10 on 2026-02-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='category',
            field=models.CharField(blank=True, choices=[('ATAQUE', 'Ataque'), ('DEFESA', 'Defesa')], max_length=20),
        ),
    ]
