# Generated by Django 6.0.2 on 2026-03-03

from django.db import migrations, models


def copy_title_to_name(apps, schema_editor):
    Play = apps.get_model("playbook", "Play")
    for p in Play.objects.all().only("id", "name"):
        # In case old DB had no name; best-effort fallback.
        if not getattr(p, "name", None):
            title = getattr(p, "title", None)
            if title:
                p.name = title
                p.save(update_fields=["name"])


class Migration(migrations.Migration):

    dependencies = [
        ("playbook", "0002_alter_play_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="play",
            old_name="title",
            new_name="name",
        ),
        migrations.AddField(
            model_name="play",
            name="formation",
            field=models.CharField(
                choices=[
                    ("shotgun", "Shotgun"),
                    ("pistol", "Pistol"),
                    ("i_formation", "I-Formation"),
                    ("trips_right", "Trips Right"),
                    ("trips_left", "Trips Left"),
                    ("spread", "Spread"),
                    ("custom", "Custom"),
                ],
                default="shotgun",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="play",
            name="play_type",
            field=models.CharField(
                choices=[("pass", "Pass"), ("run", "Run"), ("trick", "Trick")],
                default="pass",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="play",
            name="players",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="play",
            name="routes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="play",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(copy_title_to_name, reverse_code=migrations.RunPython.noop),
    ]
