# Generated by Django 6.0.2 on 2026-03-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playbook", "0003_play_designer_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="play",
            name="formation",
            field=models.CharField(default="shotgun", max_length=60),
        ),
        migrations.AlterField(
            model_name="play",
            name="play_type",
            field=models.CharField(default="pass", max_length=40),
        ),
    ]
